#!/usr/bin/env bash
# -*- mode: shell-script -*-

set -euo pipefail

set -x

if [ $# -lt 2 ]; then
    echo "Usage: $0 host nixos-cmd nixos-args..."
    exit 1
fi

host=$1
shift

out=$(nix build --json .#nixosConfigurations.${host}.config.system.build.toplevel | jq -r '.[0].outputs.out')

nix copy -s --to "ssh://root@$host" "$out"
nix copy -s --derivation --to "ssh://root@$host" "$out"

if [ "$1" = "diff" ]; then
	ssh "root@$host" "nix-store -qd /run/current-system $out | xargs nix-diff --color=always" | less
else
	ssh "root@$host" nix build --profile /nix/var/nix/profiles/system "$out"
	ssh "root@$host" nix shell -vv "$out" -c switch-to-configuration "$@"
fi
