#!/usr/bin/env bash
# -*- mode: shell-script -*-

for host in `./all-hosts`; do
	echo "====== $host ======"
	if ! ping -c1 -w3 $host >/dev/null; then
		echo "Offline, skipping"
	elif ssh $host needs-reboot; then
		echo "OK"
	fi
done
