{
  require = [
    ./archive.nix
    ./boot.nix
    ./cpufreq.nix
    ./ddc.nix
    ./desktop.nix
    ./directory.nix
    ./dns.nix
    ./firewall.nix
    ./firmware.nix
    ./flipperzero.nix
    ./gpu.nix
    ./jlink.nix
    ./kernel.nix
    ./lldp.nix
    ./microcode.nix
    #./monitoring.nix
    ./networking.nix
    ./nix.nix
    ./options.nix
    ./programs.nix
    ./shell.nix
    ./ssh.nix
    ./steam.nix
    ./tailscale.nix
    ./time.nix
    ./timezone.nix
    ./tmp.nix
    ./ulxs.nix
    ./users.nix
    ./utilities.nix
    ./virt.nix
    ./zfs.nix
    ./zrepl.nix
  ];
}
