# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ flakes, config, lib, pkgs, ... }:

{
  imports = [ flakes.nixos.nixosModules.notDetected ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "data/local/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "data/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "data/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "data/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/10DB-88AC";
      fsType = "vfat";
    };

  fileSystems."/etc/nixos" =
    { device = "data/local/etc.nixos";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
