# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "data/local/root";
      fsType = "zfs";
    };

  fileSystems."/etc/nixos" =
    { device = "data/local/etc.nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "data/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "data/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "data/safe/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/662B-6B69";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
